### ISSUE TITLE
sgmllib3k - obsolete

### ISSUE THREAD

**Issue by lbazan** [dottedmag/archmage#15]
Hi @dottedmag 

This package is a bit obsolete, I don't know if there is a way to replace it or update it?

https://pypi.org/project/sgmllib3k

Cheers,

**Comment by dottedmag** [comment]
Sure, please find a replacement, or even better, write a patch.

Also, unlike some *ahem* Javascript *ahem* other languages, I don't remember Python libraries breaking due to the passage of time.

You might be interested in the amount of maintenance this library has received while being a part of the standard library, and try to project it into the future, taking into account the number of changes accrued to SGML specification during last 33 years: https://github.com/python/cpython/commits/2.7/Lib/sgmllib.py
